# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/fenetre_chemin_dossier.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FenetreCheminDossier(object):
    def setupUi(self, FenetreCheminDossier):
        FenetreCheminDossier.setObjectName("FenetreCheminDossier")
        FenetreCheminDossier.resize(934, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(FenetreCheminDossier)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.txt_url_photo = QtWidgets.QLineEdit(FenetreCheminDossier)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txt_url_photo.setFont(font)
        self.txt_url_photo.setStyleSheet("border-bottom-color: rgb(0, 0, 0);")
        self.txt_url_photo.setObjectName("txt_url_photo")
        self.gridLayout.addWidget(self.txt_url_photo, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(FenetreCheminDossier)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.btn_select_photo = QtWidgets.QPushButton(FenetreCheminDossier)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_select_photo.setFont(font)
        self.btn_select_photo.setObjectName("btn_select_photo")
        self.gridLayout.addWidget(self.btn_select_photo, 1, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(FenetreCheminDossier)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)

        self.retranslateUi(FenetreCheminDossier)
        QtCore.QMetaObject.connectSlotsByName(FenetreCheminDossier)

    def retranslateUi(self, FenetreCheminDossier):
        _translate = QtCore.QCoreApplication.translate
        FenetreCheminDossier.setWindowTitle(_translate("FenetreCheminDossier", "Form"))
        self.label_14.setText(_translate("FenetreCheminDossier", "Dossier Photo :"))
        self.btn_select_photo.setText(_translate("FenetreCheminDossier", "Choisir"))
        self.label_15.setText(_translate("FenetreCheminDossier", "Dossiers"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FenetreCheminDossier = QtWidgets.QWidget()
    ui = Ui_FenetreCheminDossier()
    ui.setupUi(FenetreCheminDossier)
    FenetreCheminDossier.show()
    sys.exit(app.exec_())
