# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/fenetre_acceuil.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils.utilitaires import resource_path


class Ui_FenetreAcceuil(object):
    def setupUi(self, FenetreAcceuil):
        FenetreAcceuil.setObjectName("FenetreAcceuil")
        FenetreAcceuil.resize(1196, 1239)
        self.gridLayout_2 = QtWidgets.QGridLayout(FenetreAcceuil)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(FenetreAcceuil)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(resource_path("images/logos/XGEOSOFT.png")))
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(FenetreAcceuil)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(resource_path("images/logos/Rh7Bienvenu.png")))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(FenetreAcceuil)
        QtCore.QMetaObject.connectSlotsByName(FenetreAcceuil)

    def retranslateUi(self, FenetreAcceuil):
        _translate = QtCore.QCoreApplication.translate
        FenetreAcceuil.setWindowTitle(_translate("FenetreAcceuil", "Rh7"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FenetreAcceuil = QtWidgets.QWidget()
    ui = Ui_FenetreAcceuil()
    ui.setupUi(FenetreAcceuil)
    FenetreAcceuil.show()
    sys.exit(app.exec_())
