# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/fenetre_principale.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FenetrePrincipale(object):
    def setupUi(self, FenetrePrincipale):
        FenetrePrincipale.setObjectName("FenetrePrincipale")
        FenetrePrincipale.setWindowModality(QtCore.Qt.ApplicationModal)
        FenetrePrincipale.resize(1342, 896)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(FenetrePrincipale.sizePolicy().hasHeightForWidth())
        FenetrePrincipale.setSizePolicy(sizePolicy)
        FenetrePrincipale.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(FenetrePrincipale)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ui\\../images/logos/Rh7Bienvenu.png"))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("ui\\../images/logos/XGEOSOFT.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        FenetrePrincipale.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FenetrePrincipale)
        self.statusbar.setObjectName("statusbar")
        FenetrePrincipale.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(FenetrePrincipale)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1342, 26))
        self.menubar.setObjectName("menubar")
        FenetrePrincipale.setMenuBar(self.menubar)
        self.actionOuvrir = QtWidgets.QAction(FenetrePrincipale)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionFermer = QtWidgets.QAction(FenetrePrincipale)
        self.actionFermer.setObjectName("actionFermer")
        self.actionBase_personnel = QtWidgets.QAction(FenetrePrincipale)
        self.actionBase_personnel.setObjectName("actionBase_personnel")
        self.actionBase_demande = QtWidgets.QAction(FenetrePrincipale)
        self.actionBase_demande.setObjectName("actionBase_demande")
        self.actionBase_personnel_2 = QtWidgets.QAction(FenetrePrincipale)
        self.actionBase_personnel_2.setObjectName("actionBase_personnel_2")
        self.actionBase_demande_2 = QtWidgets.QAction(FenetrePrincipale)
        self.actionBase_demande_2.setObjectName("actionBase_demande_2")
        self.actionCong_s = QtWidgets.QAction(FenetrePrincipale)
        self.actionCong_s.setObjectName("actionCong_s")
        self.actionPersonnel = QtWidgets.QAction(FenetrePrincipale)
        self.actionPersonnel.setObjectName("actionPersonnel")
        self.actionDemande = QtWidgets.QAction(FenetrePrincipale)
        self.actionDemande.setObjectName("actionDemande")
        self.actionDemandes = QtWidgets.QAction(FenetrePrincipale)
        self.actionDemandes.setObjectName("actionDemandes")

        self.retranslateUi(FenetrePrincipale)
        QtCore.QMetaObject.connectSlotsByName(FenetrePrincipale)

    def retranslateUi(self, FenetrePrincipale):
        _translate = QtCore.QCoreApplication.translate
        FenetrePrincipale.setWindowTitle(_translate("FenetrePrincipale", "MainWindow"))
        self.actionOuvrir.setText(_translate("FenetrePrincipale", "Ouvrir"))
        self.actionFermer.setText(_translate("FenetrePrincipale", "Fermer"))
        self.actionBase_personnel.setText(_translate("FenetrePrincipale", "Base personnel"))
        self.actionBase_demande.setText(_translate("FenetrePrincipale", "Base demande"))
        self.actionBase_personnel_2.setText(_translate("FenetrePrincipale", "Base personnel"))
        self.actionBase_demande_2.setText(_translate("FenetrePrincipale", "Base demande"))
        self.actionCong_s.setText(_translate("FenetrePrincipale", "Congés"))
        self.actionPersonnel.setText(_translate("FenetrePrincipale", "Personnel"))
        self.actionDemande.setText(_translate("FenetrePrincipale", "Demandes"))
        self.actionDemandes.setText(_translate("FenetrePrincipale", "Demandes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FenetrePrincipale = QtWidgets.QMainWindow()
    ui = Ui_FenetrePrincipale()
    ui.setupUi(FenetrePrincipale)
    FenetrePrincipale.show()
    sys.exit(app.exec_())
