# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/fenetre_statistique.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FenetreStatistique(object):
    def setupUi(self, FenetreStatistique):
        FenetreStatistique.setObjectName("FenetreStatistique")
        FenetreStatistique.resize(1172, 609)
        self.gridLayout_2 = QtWidgets.QGridLayout(FenetreStatistique)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(FenetreStatistique)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1148, 585))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setStyleSheet("color: rgb(132, 8, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.btn_pdf = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_pdf.setMinimumSize(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_pdf.setFont(font)
        self.btn_pdf.setStyleSheet("background-color: rgb(196, 219, 255);")
        self.btn_pdf.setObjectName("btn_pdf")
        self.gridLayout.addWidget(self.btn_pdf, 3, 0, 1, 2)
        self.btn_dashboard = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_dashboard.setMinimumSize(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dashboard.setFont(font)
        self.btn_dashboard.setStyleSheet("background-color: rgb(196, 219, 255);")
        self.btn_dashboard.setObjectName("btn_dashboard")
        self.gridLayout.addWidget(self.btn_dashboard, 5, 0, 1, 2)
        self.btn_excel = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_excel.setMinimumSize(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_excel.setFont(font)
        self.btn_excel.setStyleSheet("background-color: rgb(196, 219, 255);")
        self.btn_excel.setObjectName("btn_excel")
        self.gridLayout.addWidget(self.btn_excel, 4, 0, 1, 2)
        self.comboBox_type_rapport = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_type_rapport.setFont(font)
        self.comboBox_type_rapport.setStyleSheet("border-bottom-color: rgb(0, 0, 0);")
        self.comboBox_type_rapport.setObjectName("comboBox_type_rapport")
        self.gridLayout.addWidget(self.comboBox_type_rapport, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(FenetreStatistique)
        QtCore.QMetaObject.connectSlotsByName(FenetreStatistique)

    def retranslateUi(self, FenetreStatistique):
        _translate = QtCore.QCoreApplication.translate
        FenetreStatistique.setWindowTitle(_translate("FenetreStatistique", "Form"))
        self.label_14.setText(_translate("FenetreStatistique", "Type de rapport"))
        self.label.setText(_translate("FenetreStatistique", "Statistiques"))
        self.btn_pdf.setText(_translate("FenetreStatistique", "PDF"))
        self.btn_dashboard.setText(_translate("FenetreStatistique", "Dashboard"))
        self.btn_excel.setText(_translate("FenetreStatistique", "Excel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FenetreStatistique = QtWidgets.QWidget()
    ui = Ui_FenetreStatistique()
    ui.setupUi(FenetreStatistique)
    FenetreStatistique.show()
    sys.exit(app.exec_())
